=== BlasBarragan/DAW/03_MARCAS/UD5/Activitats_DTD/mayorista.dtd
<!ELEMENT entrega (lote+)>
<!ELEMENT lote (pale+)>
<!ELEMENT pale (numcajas, contenido, peso, formamanipulacion)>
<!ELEMENT numcajas (#PCDATA)>
<!ELEMENT contenido (nombrecomponente, procedencia?, numserie, peso, unidades)>
<!ELEMENT nombrecomponente (#PCDATA)>
<!ELEMENT procedencia (pais*)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT numserie (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT formamanipulacion (#PCDATA)>

=== BlasBarragan/DAW/PRIMERO/03_MARCAS/UD5/Activitats_DTD/Actividad1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entrega SYSTEM "mayorista.dtd">
<entrega>
    <lote>
        <pale>
            <numcajas>3</numcajas>
            <contenido>
                <nombrecomponente>Fuentes</nombrecomponente>
                <numserie>3A</numserie>
                <peso>2kg</peso>
                <unidades>50</unidades>
            </contenido>
            <peso>100kg</peso>
            <formamanipulacion>Manual</formamanipulacion>
        </pale>
    </lote>
    <lote>
        <pale>
            <numcajas>2</numcajas>
            <contenido>
                <nombrecomponente>CPUs</nombrecomponente>
                <procedencia>
                    <pais>China</pais>
                    <pais>Corea del Sur</pais>
                </procedencia>
                <numserie>5B</numserie>
                <peso>100g</peso>
                <unidades>1000</unidades>
            </contenido>
            <peso>100kg</peso>
            <formamanipulacion>Manual</formamanipulacion>
        </pale>
    </lote>
</entrega>
