=== BlasBarragan/DAW/PRIMERO/03_MARCAS/UD5/XML Schema/schema9.XSD
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="llistatalumnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="ap1" type="xs:string" />
                            <xs:element name="ap2" type="xs:string" minOccurs="0" />
                            <xs:element name="edat" type="xs:positiveInteger" minOccurs="0" />
                        </xs:sequence>
                        <xs:attribute name="dni" type="dniType" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="dniType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{7,8}[A-Z]" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== BlasBarragan/DAW/PRIMERO/03_MARCAS/UD5/XML Schema/Actividad9.XML
<?xml version="1.0" encoding="UTF-8"?>

<llistatalumnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema9.xsd">
    <alumne dni="5667545Z">
      <nom>Jose</nom>
      <ap1>Sanchez</ap1>
    </alumne>
    <alumne dni="5778221D">
      <nom>Andres</nom>
      <ap1>Ruiz</ap1>
      <ap2>Ruiz</ap2>
      <edat>25</edat>
    </alumne>
  </llistatalumnes>
