=== BlasBarragan/DAW/PRIMERO/03_MARCAS/UD5/Activitats_DTD/mayorista_libros.dtd
<!ELEMENT operaciones (operacion+)>
<!ELEMENT operacion ((venta | compra)+)>
<!ELEMENT venta (titulosvendidos)>
<!ELEMENT titulosvendidos (titulo+, cantidadtotal, entregado?, importe)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cantidadtotal (#PCDATA)>
<!ELEMENT entregado EMPTY>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>
<!ELEMENT compra (tituloscomprados)>
<!ELEMENT tituloscomprados (titulo+, proveedor, fechacompra)>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT fechacompra (dia, mes, any)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>

=== BlasBarragan/DAW/PRIMERO/03_MARCAS/UD5/Activitats_DTD/Actividad2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operaciones SYSTEM "mayorista_libros.dtd">
<operaciones>
    <operacion>
        <venta>
            <titulosvendidos>
                <titulo>Don Quijote</titulo>
                <titulo>Rimas y leyendas</titulo>
                <cantidadtotal>2000</cantidadtotal>
                <importe moneda="euros">4400</importe>
            </titulosvendidos>
        </venta>
        <venta>
            <titulosvendidos>
                <titulo>Rinconete y Cortadillo</titulo>
                <titulo>Sainetes</titulo>
                <cantidadtotal>1000</cantidadtotal>
                <entregado/>
                <importe moneda="libras">290</importe>
            </titulosvendidos>
        </venta>
    </operacion>
    <operacion>
        <compra>
            <tituloscomprados>
                <titulo>De la Tierra a la Luna</titulo>
                <titulo>Barbarroja</titulo>
                <proveedor>Editorial EDSA</proveedor>
                <fechacompra>
                    <dia>10</dia>
                    <mes>6</mes>
                    <any>2018</any>
                </fechacompra>
            </tituloscomprados>
        </compra>
        <venta>
            <titulosvendidos>
                <titulo>Cinco semanas en globo</titulo>
                <titulo>Sainetes</titulo>
                <cantidadtotal>700</cantidadtotal>
                <entregado/>
                <importe moneda="euros">1490</importe>
            </titulosvendidos>
        </venta>
        <compra>
            <tituloscomprados>
                <titulo>De la Tierra a la Luna</titulo>
                <titulo>Barbarroja</titulo>
                <proveedor>Editorial Recopila</proveedor>
                <fechacompra>
                    <dia>2</dia>
                    <mes>12</mes>
                    <any>2017</any>
                </fechacompra>
            </tituloscomprados>
        </compra>
    </operacion>
</operaciones>
